services:
  order-postgres:
    image: postgres:16
    restart: unless-stopped
    networks:
      - marketplace
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d order_service_db"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 5

  order-service:
    build: .
    restart: unless-stopped
    networks:
      - marketplace
    environment:
      DATABASE_URL: "postgres://user:password@order-postgres:5432/order_service_db"
      GRPC_SERVER_ADDRESS: ":4000"
      USER_SERVICE_ADDRESS: "user-service:4000"
      PRODUCT_SERVICE_ADDRESS: "product-service:4000"
      KAFKA_BROKERS: "kafka:29092"
    depends_on:
      order-postgres:
        condition: service_healthy