services:
  product-postgres:
    image: postgres:16
    restart: unless-stopped
    networks:
      - marketplace
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d product_service_db"]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 5

  product-service:
    build: .
    restart: unless-stopped
    networks:
      - marketplace
    environment:
      DATABASE_URL: "postgres://user:password@product-postgres:5432/product_service_db"
      GRPC_SERVER_ADDRESS: :4000
    depends_on:
      product-postgres:
        condition: service_healthy
